### ISSUE TITLE
lassonet_trainer no longer exists. 

### ISSUE THREAD

**Issue by McLawrence** [lasso-net/lassonet#10]
commit [37d682e](https://github.com/lasso-net/lassonet/commit/37d682e43dbbe9c37098add7e1a4d62935f9c85d) removed the `lassonet_trainer.py` file which still is used in `experiments/evaluate.py`.  On the first glance it looks like this function is no replaced by `lassonet_utils.lassonet`, so it would make sense to change that.

**Comment by McLawrence** [comment]
Similarly, `DeepLasso12` also does not exist anymore.

**Comment by McLawrence** [comment]
`utils['lambda_min_multiplier']` and other arguments of utils are currently not set, if I've checked correctly.

**Comment by ilemhadri** [comment]
Thanks for letting us know about this.
This code is deprecated and and incompatible with the newest version of LassoNet.

If there is strong interest, we may make the experiments reproducible (again!) by releasing the up-to-date code.

Closing this in the meantime, but please feel free to re-open if appropriate.
