### ISSUE TITLE
An error when trying to run 'Usage' code in Readme

### ISSUE THREAD

**Issue by Wei-weiWang** [lasso-net/lassonet#23]
Hi,

I tried to run the code in 'Usage'. However, I encounter this error:
>>> from lassonet import LassoNetClassifierCV 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/lassonet/__init__.py", line 4, in <module>
    from .interfaces import (
  File "<fstring>", line 1
    (current_lambda=)
                   ^
SyntaxError: invalid syntax

Could you please tell me why it's like this?

**Comment by louisabraham** [comment]
I am unable to reproduce your bug. What is your version of python?

**Comment by Wei-weiWang** [comment]
python 3.9

**Comment by louisabraham** [comment]
Oh it's because the CV isn't yet pushed to PyPI. I am going to fix a few other bugs and update the PyPI version.

**Comment by Wei-weiWang** [comment]
Thank you very much!

**Comment by louisabraham** [comment]
Can you test again? run `pip install -U lassonet` first

**Comment by Wei-weiWang** [comment]
Still has this error. Sorry, my python version is 3.7.

**Comment by louisabraham** [comment]
What version of lassonet are you installing?

**Comment by Wei-weiWang** [comment]
lassonet-0.0.9

**Comment by molimi** [comment]
I try it successfully, the interface.py in lassonet reports an error here, just remove the equal sign. The code snippet is as follows：
`if is_dense and self.model.selected_count() < X.shape[1]:
    is_dense = False
    if current_lambda / lambda_start < 2:
        warnings.warn(
            f"lambda_start={self.lambda_start:.3f} "
            "might be too large.\n"
            f"Features start to disappear at {current_lambda=:.3f}."
        )  # Here is an error, just remove the equal sign`

**Comment by louisabraham** [comment]
Oh that's python 3.8 https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging

**Comment by louisabraham** [comment]
@Wei-weiWang just upgrade to python 3.8

**Comment by molimi** [comment]
@louisabraham good job，you can add a runtime environment, Python Version >= 3.8, Torch Version >= 1.11

**Comment by louisabraham** [comment]
Thanks!

I just edited the requirements (https://github.com/lasso-net/lassonet/commit/ac50fae68e932a3ec11fce010148c21a3e54c8ff)

Why should torch be > 1.11 ?

**Comment by molimi** [comment]
If Torch Version < 1.11, the following error will be reported: 

> AttributeError: module 'torch' has no attribute 'scatter_reduce'

**Comment by louisabraham** [comment]
Indeed, thanks!
