### ISSUE TITLE
how to set threads when use laaonet?

### ISSUE THREAD

**Issue by zhq90** [lasso-net/lassonet#39]
I noticed that the lassonet will use half of threads to run. I wonder to know how to use more threads when running lassonet?

**Comment by louisabraham** [comment]
Do you use the CPU or GPU?

**Comment by zhq90** [comment]
CPU

**Comment by louisabraham** [comment]
What method did you use? a -CV one?

**Comment by zhq90** [comment]
LassoNetClassifierCV

**Comment by ilemhadri** [comment]
As usual, having a fully reproducible code snippet would probably be helpful.

**Comment by louisabraham** [comment]
Well, there are multiple answers:

- you can control the number of thread used by pytorch: https://jdhao.github.io/2020/07/06/pytorch_set_num_threads/
- you could parallelize the CV loop here: https://github.com/lasso-net/lassonet/blob/e12ca78347a49af00b33aab4dba098d11634b742/lassonet/interfaces.py#L663
