### ISSUE TITLE
LassoNet-Unsupervised Feature Selection

### ISSUE THREAD

**Issue by zhangyunz** [lasso-net/lassonet#43]
Hi, 

I would like to use lassonet as an unsupervised feature selection algorithm, and I have made some attempts. However, it seems that I didn't get the correct outcome.

 
My use case:

I have an input matrix without labels, and I want to have a new reduced matrix with only several important features. I also want to know which features have been selected.

**Comment by ilemhadri** [comment]
Minimal reproducible code-snippet?

**Comment by zhangyunz** [comment]
I have made some attempts.But it seems that I didn't get the correct outcome.

![code](https://github.com/lasso-net/lassonet/assets/103341796/335a681c-d64c-4329-99c6-a60108f267dc)
![result](https://github.com/lasso-net/lassonet/assets/103341796/6ad241b0-fd65-4b3c-b6e4-b515a1675ceb)

**Comment by zhangyunz** [comment]
What should I do next regarding this issue?

**Comment by louisabraham** [comment]
Hi, what is the problem? If it is that the number of features decreases too fast, you could try a smaller `path_multiplier`.
