### ISSUE TITLE
site cannot be reached

### ISSUE THREAD

**Issue by matcyr** [lasso-net/lassonet#44]
I tried to check the page: https://lassonet.ml/ but failed. 
<img width="655" alt="Screenshot 2023-08-30 at 10 14 16 PM" src="https://github.com/lasso-net/lassonet/assets/81766154/5e446eab-9b9d-41c1-8261-8c77f212c9fa">

Could you check and update the link? Thanks!

**Comment by ilemhadri** [comment]
Thanks for bearing.

There were some issues with the previous domain name provider, and we have migrated the LassoNet website to https://lasso-net.github.io/.

Does that work?
