### ISSUE TITLE
Cannot import lassonet

### ISSUE THREAD

**Issue by RANCE-sama** [lasso-net/lassonet#45]
I have problem when i import lassonet in python3.7

File "<fstring>", line 1 
(current lambda=) 
                          ^ SyntaxError: invalid syntax

When I delete the “=” in
https://github.com/lasso-net/lassonet/blob/d740ff3153d0043301efe84903126849d9fe3f6a/lassonet/interfaces.py#L491
It works.

**Comment by RANCE-sama** [comment]
Moreover， I guess
https://github.com/lasso-net/lassonet/blob/d740ff3153d0043301efe84903126849d9fe3f6a/lassonet/utils.py#L22
should be “if not”

**Comment by louisabraham** [comment]
Please use python >= 3.8. Python 3.7 was released [5 years ago](https://endoflife.date/python). I don't think there is an error for scatter_reduce.

**Comment by RANCE-sama** [comment]
Sorry I still don’t understand. If torch has attribute "scatter_reduce_", why define a new one?

**Comment by louisabraham** [comment]
I need a different one that uses `scatter_reduce_`.

**Comment by RANCE-sama** [comment]
Thank you for your explanation (forgive my ignorance
