### ISSUE TITLE
Add documentation for LassoNetAutoEncoder

### ISSUE THREAD

**Issue by ElrondL** [lasso-net/lassonet#47]
In the example mnist_ae.py the module LassoNetAutoEncoder is imported from lassonet, but this is not in the documentation?

**Comment by ElrondL** [comment]
Does LassoNet have an autoencoder implementation? If not, is it possible to create one by connecting two LassoNetRegressors?

**Comment by louisabraham** [comment]
@ilemhadri do you know how the autoencoders were implemented in the paper?

**Comment by ilemhadri** [comment]
As of Oct 2022, it seems this used to work

```python
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler

from lassonet import LassoNetRegressor

X, _ = fetch_california_housing(return_X_y=True)
X = StandardScaler().fit_transform(X)

model = LassoNetRegressor(verbose=2)
path = model.path(X, X)
```

My reference is https://github.com/lasso-net/lassonet/issues/25

**Comment by ElrondL** [comment]
That works for me too. Is there any idea similar to a ‘latent space’ in LassoNetRegressor when used for unsupervised learning?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by ElrondL** [comment]
I’m mainly looking for a way to output the feature space

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
