### ISSUE TITLE
The link does not work

### ISSUE THREAD

**Issue by inmybrain** [lasso-net/lassonet#5]
Hi, 

I tried [https://lassonet.ml](https://lassonet.ml), but it does not work :( 

Would you be able to fix it?

**Comment by ilemhadri** [comment]
Just checked and the website is up and running. Not sure what the problem might be. Perhaps connecting from another internet connection, clearing cache, trying private browsing, etc.

**Comment by inmybrain** [comment]
This is weird. I tried different environments to access the website, but none worked. However, when I use a proxy, it works. 

I guess this happens only in my area (South Korea, maybe?).

Thanks for checking it, Ismael Lemhadri.

**Comment by louisabraham** [comment]
Hi, I tested on https://dnschecker.org/#A/lassonet.ml, they even have a South Korean server (LG Dacom Corporation in Seoul, South Korea) that reports it to be working. If you can reproduce the issue, please reopen this thread!
