### ISSUE TITLE
Running lassonet with CUDA 11.2

### ISSUE THREAD

**Issue by ElrondL** [lasso-net/lassonet#50]
Hi, is it possible to run GPU lassonet with CUDA 11.2? This is not clear in the documentation. In installation I can see that the packages are trying to install CUDA 12.3, but in my environment I have previously installed CUDA 11.2 via Conda. Does this mean that installing lassonet overwrites system’s CUDA version to 12.3? My driver cannot support 12.3 yet…

**Comment by louisabraham** [comment]
LassoNet depends on PyTorch. I'm not sure how it works, please look on https://pytorch.org/get-started/locally/
