### ISSUE TITLE
CoxPHLoss does not handle batches where all samples are censored

### ISSUE THREAD

**Issue by lenbrocki** [lasso-net/lassonet#52]
I'm training a custom model with the ```CoxPHLoss``` and have noticed that when using the Efron tie method the training will fail when a batch only contains censored events. The code giving the error is in [lassonet/utils.py](https://github.com/lasso-net/lassonet/blob/master/lassonet/utils.py):
```
if hasattr(torch.Tensor, "scatter_reduce_"):
    # version >= 1.12
    def scatter_reduce(input, dim, index, reduce, *, output_size=None):
        src = input
        if output_size is None:
            output_size = index.max() + 1
        return torch.empty(output_size, device=input.device).scatter_reduce(
            dim=dim, index=index, src=src, reduce=reduce, include_self=False
        )

else:
    scatter_reduce = torch.scatter_reduce
```
When all samples are censored ```index``` will be an empty tensor and ```index.max()``` fails. 
Also, if I understand correctly, the Cox likelihood would be zero in that case so that the log likelihood is not defined.
For now I have resorted to skipping these problematic batches, but I was thinking that it might be helpful to handle this edge case directly in ```CoxPHLoss```. Not sure what's the best way of doing it though.

**Comment by louisabraham** [comment]
Hello, can you produce a minimal reproducible example?

>  Also, if I understand correctly, the Cox likelihood would be zero in that case so that the log likelihood is not defined.

wouldn't it be one? Can you test with the Breslow approximation?

**Comment by louisabraham** [comment]
<img width="701" alt="image" src="https://github.com/lasso-net/lassonet/assets/13174805/c21ca60c-cb62-4389-8498-1276a40e6864">

I think that if the sets are empty, the log-likelihood is just zero.

**Comment by lenbrocki** [comment]
Sorry for the late response. A minimal example would be:
```
import torch
from lassonet.cox import CoxPHLoss

loss = CoxPHLoss("breslow")
labels = torch.tensor([[5.0, 0], [2.0, 0]])
hazards = torch.tensor([5.0, 2.0])
print(loss(hazards, labels)) 
#prints nan 

loss = CoxPHLoss("efron")
labels = torch.tensor([[5.0, 0], [2.0, 0]])
hazards = torch.tensor([5.0, 2.0])
print(loss(hazards, labels)) 
#fails with RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.
```

The error for the Efron method happens because of what I've described above. I think the ```nan``` in the breslow case happens because the likelihood is zero. This can for example be seen from your paper https://arxiv.org/pdf/2208.09793.pdf in equation 1: if all $\delta_i$ are zero, the product is zero and then the log of this is not defined.

**Comment by louisabraham** [comment]
I'll look at it tonight. But an empty product is 1, not 0, hence the log
will be 0.

**Comment by lenbrocki** [comment]
Oh I wasn't aware of that, but yes you're right of course. Then the problem becomes why ```nan``` is returned and not 0.

**Comment by louisabraham** [comment]
I tried a fix, can you test it?

**Comment by lenbrocki** [comment]
The CoxPHLoss now correctly returns 0. But when I'm trying to use the fixed loss in training I'm getting for batches $\delta_i = 0$ this error:
```
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

**Comment by louisabraham** [comment]
I think I managed to find a better fix :) Can you test again?

**Comment by louisabraham** [comment]
Great!
