### ISSUE TITLE
Pipeline for reproducing the experiments 

### ISSUE THREAD

**Issue by HadiHammoud44** [lasso-net/lassonet#55]
Hello,
I noticed that you provide code to load the datasets used in table 1 but do not provide the code to replicate the experiments, mentioning that it'll be possible if there is user demand. So I was wondering if you are planning on releasing the relevant code anytime **soon**, as I am working on a relevant project and it'll be much easier to have (at least) a clear pipeline to follow in order to replicate the experiments. 
Your assistance is highly appreciated!

**Comment by ilemhadri** [comment]
Closing in favor of https://github.com/lasso-net/lassonet/issues/56
