### ISSUE TITLE
importance values

### ISSUE THREAD

**Issue by chulexuexibiedebushihewo** [lasso-net/lassonet#59]
Hello! I have a question. I want to know whether "LassoNet" have function which can get something like importance values or SHAP values?

**Comment by ElrondL** [comment]
@ilemhadri How can the nominal value of model.feature_importances_ for each dimension in X be interpreted? How can they be used to select features quantitatively? cc @louisabraham

**Comment by louisabraham** [comment]
They are lambda values as said above. I'm working on a tutorial to explain stability selection that might be useful too.
