### ISSUE TITLE
unable to get repr for lassonet class

### ISSUE THREAD

**Issue by wowSUNBOY** [lasso-net/lassonet#6]
Hi, thank you so much for your wonderful code.
But I have some problems in my practice, in debug mode of Pycharm, it indicated "reg: Unable to get repr for <'class 'lassonet.interfaces.LassoNetRegressor'>"    as in the below picture
Is my python package version not right?
Thank you very much!
Look forward to your reply.

![image](https://user-images.githubusercontent.com/34408131/122020184-d671d300-cdc4-11eb-9fbf-52ce0ed4120f.png)

**Comment by louisabraham** [comment]
Hi, thanks for using LassoNet!
Thanks for reporting this, I think it's due to some sklearn functions I did not implement yet. Will try to fix it asap!

**Comment by wowSUNBOY** [comment]
Thank you for your reply!! I am using .path function now. it is okay and I can get the results now.
Also, during the network training, I do not find the batch_size parameter, Can you help me find it?
Thank you so much!

**Comment by louisabraham** [comment]
I think I solved the repr problem, you can install the latest version (before it's pushed on PyPI) with `pip install git+https://github.com/lasso-net/lassonet`.

We are implementing batched optimization, please bear with us!

**Comment by louisabraham** [comment]
Just pushed a new version with batch_size if you want to test it!

**Comment by wowSUNBOY** [comment]
Thank you for your update! But I have problem in updating the package, I execute the pip command but in jupyter I still can not find the batch_size parameter. As blow is my terminal response, Did I fail to update it successfully?
![image](https://user-images.githubusercontent.com/34408131/122185370-57949d00-ce8d-11eb-92e7-d6a6e84d3b00.png)

**Comment by louisabraham** [comment]
weird, can you try `pip install -U git+https://github.com/lasso-net/lassonet`?

**Comment by wowSUNBOY** [comment]
Thank you for your advice. I have tried this command, the result in termial is same.
And in jupyter, I think the package is still the old version, as below
![image](https://user-images.githubusercontent.com/34408131/122189391-2ddd7500-ce91-11eb-8ccc-e99f09238181.png)

**Comment by louisabraham** [comment]
Did you restart you interpreter / notebook kernel?

**Comment by wowSUNBOY** [comment]
Yes, I did restart my jupyter notebook.
So in my package, lambda_seq and batch_size are both not available.
It should be something wrong in my package or anaconda I think.

**Comment by louisabraham** [comment]
I don't know at all, maybe you have two python installations. I recommend https://pythondiscord.com/ to quickly get help on such matters!

**Comment by wowSUNBOY** [comment]
Thank you so much!
