### ISSUE TITLE
Quick question on selection probability

### ISSUE THREAD

**Issue by ElrondL** [lasso-net/lassonet#63]
Hi Devs,

Thank you so much for continuing to work on this important project. How does the selection probability translate to feature selection in practice (i.e. how to use it to identify a minimal set of feature that can well represent the input)?

https://github.com/fabian-sp/lassonet
Also, I discovered this custom implementation of LassoNet but with varying architectures; it could be useful for general research purposes and I don't know if you've already seen this work.

**Comment by louisabraham** [comment]
Thank you for your question. The answer will appear in the latest version of this paper that we have to put online in the following weeks @garcia-mc
https://arxiv.org/abs/2206.06885

We exchanged a few emails back then with @fabian-sp
I think @p-smirnov explored the idea of L1 for convnets but I'm not sure if it led to a publication.

**Comment by ElrondL** [comment]
Glad that you guys are still working on this. Thank you!
