### ISSUE TITLE
Option to stop training if a lower limit of selected features is reached

### ISSUE THREAD

**Issue by barveaditya** [lasso-net/lassonet#66]
Hello, 

I do not see a method to stop training when the lower limit of selected features is reached. Is there? If not, that would be a handy feature instead of going all the way to 0 selected features. For example, I am dealing with a reconstruction/regression of all features problem, and my lower limit of selected features is around 500 out of around 8000. 

Regards
Aditya

**Comment by louisabraham** [comment]
Hi and thank you for reaching out! I think this use case is very specific and is a convenience optimization so we won't implement it.

If you really need to, you can force the training to stop whenever you want by manually setting the weights to 0 using the `callback` argument.
