### ISSUE TITLE
Doc is still not very clear on Stability Selection...

### ISSUE THREAD

**Issue by ElrondL** [lasso-net/lassonet#67]
Hey Devs,

Just providing feedbacks from first use experience here ^ ^ It's still not very clear how to actually use stability_selection() to choose a group of stable features.

Running madelon.py will give an oracle of '0' optimal number of features (torch ~1.12.1, LassoNet 0.19.0). 
I guess one way to select will be to refer to the 'prob' matrix, and look up at selection probability at which the model score experiences an inflection point (sudden increase in drop of model performance with respect to number of features selected)? But can't do this because 'wrong' is linear with respect to features, and paths contain 500 individual path objects. 

I think madelon has 5 true main factors and 15 interaction factors?

It looks like the 'prob' matrix used a path that had 292 lambda steps, and I can use that to look up the specific 'path' object that produced the 'prob' matrix from 'paths'

**Comment by louisabraham** [comment]
Hello! Madelon might not be a good example, I committed it by error.

The more interesting part would be to:
- select the k best features by using the `wrong` array
- plot the trajectories using `prob` like in the spinet example.

I'm welcome for any edit of the README!

**Comment by louisabraham** [comment]
You can also train a model for each of the k first best features selected according to `order`.

**Comment by ElrondL** [comment]
Hey Louis,
thanks so much for the swift reply. There is a bug in spinet; Line 27 calls (plt.plot([1 - s.mean() for s in prob], prob)) but prob is a tensor..

**Comment by louisabraham** [comment]
Thanks, could you fix it with `s.mean(dim=1)`? I won't be able to do it today but I can accept the PR.

**Comment by ElrondL** [comment]
Hey Louis, 
Certainly ! Trying the suggested fix will give an error saying s only has dimensions [-1, 0]..

**Comment by ElrondL** [comment]
And trying s.mean(dim=0) will give 

ValueError: only one element tensors can be converted to Python scalars
....

**Comment by louisabraham** [comment]
Hello, I cannot seem to reproduce your error.

<img width="464" alt="image" src="https://github.com/user-attachments/assets/0858a74d-f562-4a35-bcf7-5ac6ee81f18b">

**Comment by ElrondL** [comment]
Hi,

What is your PyTorch version? I’m still using PyTorch 1. Could that have an effect ?

On Sep 25, 2024, at 20:09, Louis Abraham ***@***.***> wrote:

﻿

Hello, I cannot seem to reproduce your error.

image.png (view on web)<https://github.com/user-attachments/assets/0858a74d-f562-4a35-bcf7-5ac6ee81f18b>

**Comment by ElrondL** [comment]
prob is (456, 100). It is impossible to plot a list of length 456 ([1 - s.mean() for s in prob]) the against a 2D thing of shape (456, 100)

plt.plot([1 - s.mean() for s in prob], prob)

**Comment by louisabraham** [comment]
I have `2.3.1`. You should definitely upgrade pytorch :)

**Comment by ElrondL** [comment]
Hi Louis
No it's still bugged.
I have torch 2.4.0 now

when I run this, prob is a tensor of (467, 100). Of course it's going to give
ValueError: only one element tensors can be converted to Python scalars

when running
plt.plot([1 - s.mean() for s in prob], prob)

Because it's trying to plot a 1D list of x against a 2D matrix of y, which doesn't make any sense?
prob is 2D for me; is prob 2D for you ? I am not trolling.

**Comment by ElrondL** [comment]
<img width="1010" alt="Screenshot 2024-09-26 at 12 21 08" src="https://github.com/user-attachments/assets/8f7e3aef-da4f-45cf-a721-e42d83f770b0">

What actually is the y in this graph? It looks like it plotted one curve for each of the 100 or 467 members of prob?

**Comment by ElrondL** [comment]
@louisabraham I got it. If you upgrade Matplotlib lib to 3.9.2 it works. It doesn't work for 3.8.0!! 

I still need some help with what y means though 

(edit) nvm I will just read https://www.stat.cmu.edu/~ryantibs/journalclub/stability.pdf. TYSM !!
