### ISSUE TITLE
Support for CNNs and/or auto-encoders?

### ISSUE THREAD

**Issue by ShailenSmith** [lasso-net/lassonet#70]
Hi,

My lab is working on some research with image classification models, and we are looking for some computationally inexpensive methods for embedded feature selection on the pixels of images. The readme mentions that the LassoNet team is currently working to add support for convolutional layers and auto-encoders -- may I ask if there are any updates on this front?

In my mind the primary challenge for applying a lasso-like method to CNNs is the lack of weights that are tied to specific pixels in the image. Any insights on how this could be done?

Thanks for your help!

**Comment by louisabraham** [comment]
The goal of LassoNet is feature selection, so you have to decide whether you want to select individual pixels or higher level features.
- individual pixels : you could add a lassonet layer at the beginning of your network, constrained by a skip connection that goes to the output or to another layer. We did this without any CNN in the paper on MNIST.
- higher level features : you can use a CNN as encoder then apply standard lassonet.
