### ISSUE TITLE
StopIteration Error

### ISSUE THREAD

**Issue by ShijianXu** [lasso-net/lassonet#72]
Dear Authors,

I am trying to reproduce the results by running the `run.py` file in the folder `experiments`. The dataset I am using is MICE. However, I encoutered the following error:

```
X shape: (1080, 77), Y shape: (1080,)
Number of selected features: 38
Traceback (most recent call last):
  File "/home/xu0005/Desktop/lassonet/experiments/run.py", line 60, in <module>
    path_sparse = lasso_sparse.path(
  File "/home/xu0005/miniconda3/envs/pytorch/lib/python3.9/site-packages/lassonet/interfaces.py", line 465, in path
    lambda_start = next(lambda_seq)
StopIteration
```

The running just stopped without any further log out. I am not sure about what happened. Could you please help check this problem? Thank you very much.

**Comment by louisabraham** [comment]
Do not pass a single value for lambda_seq.

**Comment by ShijianXu** [comment]
Thank you for the reply. Then in this case, I think the sample code in the repo (i.e., the `run.py` under folder `experiments`) needs to be updated, as only a single value for lambda_seq was passed.
