### ISSUE TITLE
Check for presence of cuda is not being saved to self

### ISSUE THREAD

**Issue by p-smirnov** [lasso-net/lassonet#9]
I think there is a bug in the following lines:
https://github.com/lasso-net/lassonet/blob/3b3b529d872ef6ea56ff61ec6fbc93beff1e4d03/lassonet/interfaces.py#L132-L134

device is set to CUDA is torch reports that cuda is available, but its done after self.device is already set.

**Comment by louisabraham** [comment]
Thanks! Btw I didn't test it on GPU and I think that loading models might fail so please report me the bugs!
